mrs_uav_managers:

  estimation_manager:

    state_estimators: [
    "gps_baro",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: ""

  control_manager:

    Se3Controller:
      eland_threshold: 4.0 # [m], position error triggering eland
      failsafe_threshold: 8.0 # [m], position error triggering failsafe land
      odometry_innovation_threshold: 1.5 # [m], position odometry innovation threshold

    # list of names of dynamically loaded trackers
    trackers : [
      "FlipTracker",
    ]

    safety:

      tilt_limit:

        eland:
          enabled: false

        disarm:
          enabled: false

      yaw_error_eland:
        enabled: false

      tilt_error_disarm:
        enabled: false

  constraint_manager:

    default_constraints:
      gps_baro: "fast"

  uav_manager:

    max_throttle:

      enabled: false

    takeoff:

      takeoff_height: 3.0

      after_takeoff:
        controller: "Se3Controller"

    min_height_checking:
      enabled: false

    max_height_checking:
      enabled: false

mrs_uav_controllers:

  se3_controller:

    constraints:

      tilt_angle_failsafe:
        enabled: false
