mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "rtk",
      "gps_baro",
      "gps_garmin",
    ]

    initial_state_estimator: "rtk" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  constraint_manager:

    default_constraints:

      rtk: "medium"

  uav_manager:

    takeoff:
      after_takeoff:
        controller: Se3Controller

    landing:
      disarm: true

