simulation_rate: 250.0 # Hz
clock_rate: 250.0 # Hz
realtime_factor: 1.0

iterate_without_input: true

uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
  "uav6",
  "uav7",
  "uav8",
  "uav9",
  "uav10",
  "uav11",
  "uav12",
]

uav1:
  type: "t650"
  spawn:
    x: 10.0
    y: 10.0
    z: 1.0
    heading: 0.0

uav2:
  type: "t650"
  spawn:
    x: -10.0
    y: 10.0
    z: 1.0
    heading: 0.0

uav3:
  type: "t650"
  spawn:
    x: -10.0
    y: -10.0
    z: 1.0
    heading: 0.0

uav4:
  type: "t650"
  spawn:
    x: 10.0
    y: -10.0
    z: 1.0
    heading: 0.0

uav5:
  type: "t650"
  spawn:
    x: 30.0
    y: 10.0
    z: 1.0
    heading: 0.0

uav6:
  type: "t650"
  spawn:
    x: 30.0
    y: 30.0
    z: 1.0
    heading: 0.0

uav7:
  type: "t650"
  spawn:
    x: 10.0
    y: 30.0
    z: 1.0
    heading: 0.0

uav8:
  type: "t650"
  spawn:
    x: -10.0
    y: 30.0
    z: 1.0
    heading: 0.0

uav9:
  type: "t650"
  spawn:
    x: -30.0
    y: 30.0
    z: 1.0
    heading: 0.0

uav10:
  type: "t650"
  spawn:
    x: -30.0
    y: 10.0
    z: 1.0
    heading: 0.0

uav11:
  type: "t650"
  spawn:
    x: -30.0
    y: -10.0
    z: 1.0
    heading: 0.0

uav12:
  type: "t650"
  spawn:
    x: 30.0
    y: -10.0
    z: 1.0
    heading: 0.0
