active: true
main_timer_rate: 100 # [Hz]

use_heading: true
relax_heading: true

z:
  value: 1.5 # [m]
  deviation: 0.5 # [m]

n_points:
  min: 10 # [-]
  max: 15 # [-]

point_distance:
  min: 1.5 # [m]
  max: 3.0 # [m]

future_stamp:
  prob: 1.0 # [0, 1]
  min: 2.0 # [s]
  max: 4.0 # [s]

replanning_time:
  min: 4.0 # [s]
  max: 5.0 # [s]

heading_change: 3.14 # [rad]
bearing_change: 0.78 # [rad]
