#
## DEFINITION OF THE ARENA
#

world_origin_units: "LATLON" # {"UTM, "LATLON"}

world_origin_x: 47.397743
world_origin_y: 8.545594

safety_area:

  use_safety_area: true

  frame_name: "world_origin"

  # convex polygon CCW
  safety_area: [
    47, 47,
    22, 47,
    22, 22,
    -22, 22,
    -22, 47,
    -47, 47,
    -47, -25,
    -25, -47,
    47, -47
  ]

  max_z: 15.0
  min_z: 0.5

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: true

    data: [-37.2, -20.1,  23.5,  18.0, -16.7, -25.8, -27.6, -37.2,
           -19.0, -35.5, -34.5, -26.8, -26.5, -17.2,  -2.5,  -2.6]

    rows: 2 # each matrix has two rows
    cols: [8] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: true

    data: [0, 0, 2.5, 5,
    35, 35, 2.5, 5,
    25, 0, 2.5, 5,
    35, -35, 2.5, 5,
    0, -25, 2.5, 5,
    -35, 35, 2.5, 5,
    -25, 0, 2.5, 5]

    rows: 1 # each matrix has a single row
    cols: [4, 4, 4, 4, 4, 4, 4] # nums of cols of each matrix

