mrs_uav_managers:

  control_manager:

    Se3Controller:
      eland_threshold: 4.0 # [m], position error triggering eland
      failsafe_threshold: 8.0 # [m], position error triggering failsafe land
      odometry_innovation_threshold: 1.5 # [m], position odometry innovation threshold

    MpcController:
      eland_threshold: 4.0 # [m], position error triggering eland
      failsafe_threshold: 8.0 # [m], position error triggering failsafe land
      odometry_innovation_threshold: 1.5 # [m], position odometry innovation threshold

    trackers: [
      "LineTracker",
    ]

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "gps_baro",
      "gps_garmin",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  constraint_manager:

    default_constraints:

      gps_baro: "fast"
      gps_garmin: "fast"
      ground_truth: "fast"

  uav_manager:

    takeoff:
      after_takeoff:
        controller: "Se3Controller"

    landing:
      disarm: true
